# For development test
version: "3.8"

services:
  db:
    image: postgres:17-trixie
    restart: always
    environment:
      - POSTGRES_USER=hilo_user
      - POSTGRES_PASSWORD=hilo_pass
      - POSTGRES_DB=hilo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hilo_user -d hilo_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Read the values from the .env file or environment
        # USER_ID: ${MY_UID}
        # GROUP_ID: ${MY_GID}
    extra_hosts:
      - "host.containers.internal:host-gateway"
    ports:
      - "8090:8090"
      - "8091:8091"
      # - "8092:8092"
    environment:
      ALLOWED_DOMAINS: "mails.tsinghua.edu.cn:stu.pku.edu.cn"
      ALLOWED_GRADES: "undergraduate:graduate"
      JWT_SECRET: "a-very-long-secret-for-jwt-only-for-test"
      EMAIL_PROVIDER: "external"
      MAIL_API_URL: "http://host.containers.internal:8092"
      MAIL_API_KEY: "test-api-key"
      SENDER_EMAIL: "hilo dev"
      DATABASE_URL: "postgres://hilo_user:hilo_pass@db:5432/hilo_db"
      RUST_LOG: "info,hilo=debug"
      LOG_FORMAT: "plain"
      ADDRESS: "0.0.0.0:8090"
      ADMIN_ADDRESS: "0.0.0.0:8091"
      UPLOAD_DIR: "/home/appuser/uploads"
      TAGS_LIMIT_SUM: 10
      TRAITS_LIMIT_EACH: 3
      TAG_SCORE_DECAY_FACTOR: 0.5
      COMPLEMENTARY_TAG_WEIGHT: 0.8
      TRAIT_MATCH_POINTS: 2.0
      MAX_PREVIEW_CANDIDATES: 6

    depends_on:
      db:
        condition: service_healthy
    volumes:
      - app_uploads:/home/appuser/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8090/health-check"]
      interval: 1m
      timeout: 5s
      start_period: 3s
      start_interval: 1s
    working_dir: /home/appuser

volumes:
  postgres_data:
  app_uploads:
